### ISSUE TITLE
add notice on contributing to README

### ISSUE THREAD

**Issue by Frikki** [motorcyclejs/motorcycle-core#20]
### Overview

Add notice on contributing to avoid poorly described issues from users.

### Motivation

Users are likely to read the *README*, but may miss the *CONTRIBUTING* document in the repo. The *CONTRIBUTING* document describes in detail what to include when reporting issues, so to minimize the chance of poorly described issues, we should add a notice.

**Comment by TylorS** [comment]
Good thinking. We should put this on motorcyclejs/motorcycle as it'd be a good thing for all the repos.

**Comment by Frikki** [comment]
My thoughts exactly.

**Comment by Frikki** [comment]
I actually want to put the *CONTRIBUTING* document in the *motorcycle* repo, and then just have simple *CONTRIBUTING* documents in the various repos that link to the main repo.

**Comment by TylorS** [comment]
We should put links at the top of the README's
# Want to contribute?
Have an issue? [Read this first](https://github.com/motorcyclejs/motorcycle-core/blob/develop/CONTRIBUTING.md#submitting-an-issue)

Something like that

**Comment by Frikki** [comment]
Agreed.
