### ISSUE TITLE
add options parameter to `run()`

### ISSUE THREAD

**Issue by Frikki** [motorcyclejs/motorcycle-core#23]
### Overview

Add an optional options parameter to `run()`, like:

```js
function run(<Function>mainFunc, <Object>sources, <Object>options)
```

Where `options` could be:

```js
const options = {debug:true}
```

... to allow debug messages in console.

### Motivation

If a `sinks[name]` stream ends for some reason, whether it be a poor driver implementation or alike, and for some reason the stream is not infinite, it could output:

```js
console.log(`${name} completed.`)
```

**Comment by TylorS** [comment]
I believe this could this would be very helpful for at least 2 reasons.

1. Developing drivers
  One can better know if your streams are operating as intended. Whether they are 
  terminating early, or creating some kind of undesired behavior.
2. Developing applications
  Allows users to understand what is going on throughout their application
  i.e. A driver or component is outputting too often or too little.

**Comment by Frikki** [comment]
I’d like to get @staltz’ comment, too.

**Comment by staltz** [comment]
I would rather have this option given to a driver. That's why the convention for drivers is usually `makeBleshBlosh()` and not `bleshBlosh()` because with a factory function we have the opportunity of specifying options. It shouldn't be complicated to add this debug option to the most important drivers.

**Comment by TylorS** [comment]
@staltz You're probably correct. Reason 2 is easily solved by that, and 1 is irrelevant because if you're developing a driver you're in control of the stream anyways.

**Comment by staltz** [comment]
I won't say I'm correct, but we should be careful when **adding** anything to (Motor)Cycle.js. It is very easy to make the API grow, but very hard to keep it small. As Cycle.js developed from 0.1 to 1.0, I basically deleted a lot of API.

**Comment by Frikki** [comment]
I am also in favor of less parameters and minimal APIs.

I guess, we can close this issue then?

**Comment by TylorS** [comment]
I think so.
