### ISSUE TITLE
add changelog

### ISSUE THREAD

**Issue by Frikki** [motorcyclejs/motorcycle-core#6]
For an easy overview of the progression of the project, we should generate a changelog from commit messages. To automate this, it is important that commit messages adhere to our guidelines. A way to ensure this, to some degree, is to have a commit message validation git-hook as development dependency.

**Comment by Frikki** [comment]
I’d like to hear your feedback on such a hook, @TylorS

**Comment by TylorS** [comment]
Automate all the things!

I think that this is a great idea, uniformity and high quality commits would certainly be a good thing for anyone who does or would like to contribute. Change logs being automatically generated would definitely be an (awesome!) added bonus.

**Comment by Frikki** [comment]
Great. I’ll set it up. I have the tools in my luggage.

**Comment by Frikki** [comment]
Automation is related to issue #9.
