### ISSUE TITLE
lock dependencies down

### ISSUE THREAD

**Issue by Frikki** [motorcyclejs/motorcycle-core#7]
As there is no guarantee that dependencies adhere to the rules of semantic versioning, to avoid developers having different versions, we should lock the dependencies down.

**Comment by TylorS** [comment]
I'm thinking that this would be a good thing to do for a 1.0.0 release. What do you think?

**Comment by Frikki** [comment]
This is a good thing to do *now*. We avoid developing using possibly different dependency versions. I see no reason to wait.

**Comment by TylorS** [comment]
Alright, we'll take care of this ASAP then.

**Comment by Frikki** [comment]
I’ll assign myself to it, if no objections.

**Comment by TylorS** [comment]
Works for me :+1:
